version: '2'
# 定义服务tomcat,mysql,redis
services:

  # JAVA-TOMCAT
  tomcat:
    depends_on:
      - mysql
      - redis
    
    image: wisbyme/tomcat:8.5.47
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tomcat/webapps:/usr/java/tomcat/webapps
      - ./tomcat/conf/server.xml:/usr/java/tomcat/conf/server.xml
      - ./tomcat/conf/tomcat-users.xml:/usr/java/tomcat/conf/tomcat-users.xml
      - ./tomcat/conf/web.xml:/usr/java/tomcat/conf/web.xml
      - ./tomcat/conf/context.xml:/usr/java/tomcat/conf/context.xml

    restart: always
    ports:
      - "808:8080"
      - "443:8443"

    container_name: tomcat


  # MySQL
  mysql:
    image: wisbyme/mysql:5.7.27

    ports:
      - "127.0.0.1:3306:3306"
      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./log/mysql.log:/var/log/mysql/error.log
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      
    environment:
      MYSQL_ROOT_PASSWORD: $MySQLpwd
      
    command: ['mysqld', '--character-set-server=utf8']
    
    restart: always
    container_name: mysql

  # REDIS
  redis:
    image: wisbyme/redis:5.0.5
    
    ports:
      - "127.0.0.1:6379:6379"
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./log/redis.log:/usr/local/redis/redis.log

    restart: always
    container_name: redis

